-- GROUP BY
-- 카테고리 별 도서 판매량 집계하기
SELECT
    b.CATEGORY,
    SUM(a.SALES) AS TOTAL_SALES
FROM
    BOOK_SALES a
    JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
WHERE
    SALES_DATE LIKE '2022-01-%'
GROUP BY
    b.CATEGORY
ORDER BY
    CATEGORY